spring:
  application:
    name: auth-server
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
server:
  port: 9000

client:
  secret: "{bcrypt}$2a$10$KvZEC7QF/apVZANTewB3q.Z/XMZFKPTNV6ez/NLdsYG20OJZy71Hy"

logging:
  level:
    org.springframework.security: DEBUG