spring:
  application:
    name: auth-server
  security:
    oauth2:
      authorizationserver:
        issuer: http://localhost:9000
server:
  port: 9000

client:
  password: my-password

logging:
  level:
    org.springframework.security: DEBUG